#!/bin/bash

echo "--- Mise en Production ---"
cd /home/sc2lama8699/syl_mia/prod
unset GIT_DIR
git pull origin main

echo "--- Mise en Développement ---"
cd /home/sc2lama8699/syl_mia/dev
unset GIT_DIR
git pull origin dev
